# Generated by Django 5.2 on 2025-05-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choice_text",
            new_name="choice_txt",
        ),
    ]
