# Generated by Django 5.2 on 2025-05-07 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_choice_text_choice_choice_txt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Published on"
            ),
        ),
    ]
