# Generated by Django 5.2 on 2025-05-21 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_question_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="votes",
            new_name="vote_count",
        ),
        migrations.AddField(
            model_name="question",
            name="allows_multiple_choices",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
