# Generated by Django 5.2 on 2025-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.CharField(default="", max_length=220),
        ),
    ]
