# Generated by Django 5.2 on 2025-05-24 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_alter_question_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="Poll",
        ),
    ]
