# Generated by Django 5.2 on 2025-05-24 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_rename_question_poll"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_vote_per_poll",
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="question",
            new_name="poll",
        ),
        migrations.RenameField(
            model_name="poll",
            old_name="question_txt",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="question",
            new_name="poll",
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user", "poll", "choice"), name="unique_vote_per_poll"
            ),
        ),
    ]
