# Generated by Django 5.2 on 2025-05-25 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_remove_vote_unique_vote_per_poll_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=models.CharField(blank=True, default="", max_length=220),
        ),
        migrations.AddConstraint(
            model_name="poll",
            constraint=models.CheckConstraint(
                condition=models.Q(("deadline__gt", models.F("created_at"))),
                name="deadline_not_in_past",
            ),
        ),
    ]
