# Generated by Django 5.2 on 2025-05-25 18:21

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_alter_poll_description_poll_deadline_not_in_past"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="poll",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("deadline__gte", django.db.models.functions.datetime.Now()),
                        ("is_active", False),
                    ),
                    models.Q(
                        ("deadline__lt", django.db.models.functions.datetime.Now()),
                        ("is_active", True),
                    ),
                    _connector="OR",
                ),
                name="is_active_matches_deadline",
            ),
        ),
    ]
