# Generated by Django 5.2 on 2025-05-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_poll_is_active_poll_is_active_matches_deadline"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="poll",
            name="is_active_matches_deadline",
        ),
    ]
