# Generated by Django 5.2 on 2025-05-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_remove_poll_is_active_matches_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="is_active",
        ),
    ]
